version: '3'
services:
  my_redis:
    image: redis
    container_name: my_redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - my-network

  my_mongo:
    image: mongo
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network

  danmaku_top:
    image: richard1227/danmaku_top
    container_name: danmaku_top
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - my_redis

  danmaku_top_frontend:
    image: richard1227/danmaku_top_frontend
    container_name: danmaku_top_frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - danmaku_top

  my_nginx:
    image: nginx
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/danmaku_top_nginx.conf:/etc/nginx/conf.d/danmaku_top_nginx.conf
      - ${CRT_PATH}:/etc/ssl/certs/nginx.crt
      - ${KEY_PATH}:/etc/ssl/private/nginx.key
    depends_on:
      - danmaku_top
    networks:
      - my-network

networks:
  my-network:

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local