version: '3'
services:
  my_redis:
    image: redis
    container_name: my_redis
    volumes:
      - "/redis_data"
    ports:
      - "6379:6379"
    networks:
      - my-network

  danmaku_top:
    image: richard1227/danmaku_top
    container_name: danmaku_top
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - my_redis

  my_nginx:
    image: nginx
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - danmaku_top
    networks:
      - my-network

networks:
  my-network: