version: '3'
services:
  redis:
    image: redis
    volumes:
      - "/redis_data"
    ports:
      - "6379:6379"
    networks:
      - my-network

  danmaku_top:
    image: richard1227/danmaku_top
    networks:
      - my-network

networks:
  my-network: